# Site information
theme: jekyll-theme-cayman
title: Dirty Chai
description: A page on the World Wahid Web
show_downloads: false
baseurl: ""
url: "https://dirtychai.net"

# Site settings
markdown: kramdown

header_page_refs: ['now', 'about', 'contact']
