# Site information
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Dirty Chai
description: by Wahid Khan
show_downloads: false
baseurl: ""
url: "https://dirtychai.net"

# Site settings
markdown: kramdown

header_page_refs: ['now', 'about', 'contact']
